## Remember Vectors and Matrices?
In your previous math courses, you learned the concept of vectors and matrices. In CSMODEL we would also be using vectors and matrices. However, instead of using pen and paper, we are going to use Python to define vectors and matrices and perform operations on them. In this Notebook, we will see how we can represent vectors and matrices using NumPy, a useful package for Python for mathematical operations.

Our Notebooks in CSMODEL are designed to be guided learning activities. To use them, simply through the cells from top to bottom, following the directions along the way. If you find any unclear parts or mistakes in the Notebooks, kindly raise your concerns in the Discussion forums in our AnimoSpace or email me at thomas.tiam-lee@dlsu.edu.ph.

## NumPy
**NumPy** is a library for the Python programming language. It contains a large collection of mathematical functions, as well as convenient data structures to represent vectors and matrices. To use NumPy, we first need to import it.

In [2]:
import numpy as np

Now, we can access the functionalities of NumPy through the `np` variable.

## Creating Vectors and Matrices

A vector is a list of numbers, which could be in a row or in a column. To create vectors in NumPy, we simply use the `np.array` function. To create this vector:
\begin{equation*}
\begin{bmatrix}
2 & 4 & 6
\end{bmatrix}
\end{equation*}

In [3]:
v = np.array([2, 4, 6])
v

array([2, 4, 6])

The vector above is a 1-dimensional vector. However, sometimes, you would want to define a row vector or a column vector. In this case, you can use a 2-dimensional array to initialize the vector.

To create this row vector:
\begin{equation*}
\begin{bmatrix}
2 & 4 & 6
\end{bmatrix}
\end{equation*}

In [4]:
v = np.array([[2, 4, 6]])
v

array([[2, 4, 6]])

To create this column vector:
\begin{equation*}
\begin{bmatrix}
2 \\
4 \\
6
\end{bmatrix}
\end{equation*}

In [5]:
v = np.array([[2],
              [4],
              [6]])
v

array([[2],
       [4],
       [6]])

A matrix is a rectangular array arranged in rows and columns. To create matrices in NumPy, we also use the `np.array` function.

To create this matrix:
\begin{equation*}
\begin{bmatrix}
1 & 2  & 3  & 4  \\
5 & 6  & 7  & 8  \\
9 & 10 & 11 & 12
\end{bmatrix}
\end{equation*}

In [6]:
A = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

To create this matrix:
\begin{equation*}
\begin{bmatrix}
10 &  20 \\
30 &  40 \\
50 &  60 \\
70 &  80 \\
90 & 100
\end{bmatrix}
\end{equation*}

In [7]:
A = np.array([[10,  20],
              [30,  40],
              [50,  60],
              [70,  80],
              [90, 100]])
A

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

You can `np.zeroes` to create a vector or matrix full of 0s. Note that the parameter of this function is a **tuple** representing the shape. In NumPy, **shape just refers to the dimensions of the array**.

In [8]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

You can also use `np.ones` to create a vector or matrix full of 1s.

In [9]:
np.ones((7, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Indexing

You can index a specific element from the vector using array-style indexing. Note the use of **negative indices** as discussed in the previous Notebook. You may play around the indices here to experiment.

In [10]:
# this cell has no output, but be sure to execute it because the next cells use the variables created here
v = np.array([10, 20, 30, 40, 50, 60, 70, 80])
A = np.array([[ 2,  4,  6],
              [ 8, 10, 12],
              [14, 16, 18]])

In [13]:
v[5]

60

In [14]:
v[-5] # -2 means second to the last element.

40

In [17]:
A[1,2]

12

In [18]:
A[-1,-1] # -1 means the last element

18

You can select an entire row or column of a matrix by using slicing techniques on either dimension.

In [21]:
# this cell has no output, but be sure to execute it because the next cells use the variables created here
A = np.array([[ 2,  4,  6],
              [ 8, 10, 12],
              [14, 16, 18]])

In [24]:
# Select the first row of A
A[0,:]

array([2, 4, 6])

In [25]:
# Select the second column of A
A[:,1]

array([ 4, 10, 16])

In [26]:
# Select the last column of A
A[:,-1]

array([ 6, 12, 18])

And by extension, you can select any subset of a matrix by using slicing operations.

In [27]:
# this cell has no output, but be sure to execute it because the next cells use the variables created here
A = np.array([[ 2,  4,  6,  8, 10],
              [12, 14, 16, 18, 20],
              [22, 24, 26, 28, 30],
              [32, 34, 36, 38, 40],
              [42, 44, 46, 48, 50]])

In [30]:
# Select the first 3 rows of A
A[:3,:]

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [31]:
# Select the last 2 rows of A
A[-2:,:]

array([[32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [32]:
# Select the last 3 columns A
A[:,-3:]

array([[ 6,  8, 10],
       [16, 18, 20],
       [26, 28, 30],
       [36, 38, 40],
       [46, 48, 50]])

In [33]:
# Select the 3x3 sub-matrix from the top left corner of A
A[0:3,0:3]

array([[ 2,  4,  6],
       [12, 14, 16],
       [22, 24, 26]])

**Practice!** Select the number 14 from the matrix `X`.

In [35]:
X = np.array([[ 2,  4,  6],
              [ 8, 10, 12],
              [14, 16, 18]])

# Write your expression here
X[2,0]

14

**Practice!** Select the third row from the matrix `Y` (the one with 1s).

In [37]:
Y = np.array([[0, 0, 0, 0],
              [0, 0, 0, 0],
              [1, 1, 1, 1],
              [0, 0, 0, 0],
              [0, 0, 0, 0],
              [0, 0, 0, 0]])

# Write your expression here
Y[2,:]

array([1, 1, 1, 1])

**Practice!** Select the first three columns from `C`, but exclude the last row which only contains zeroes.

In [38]:
C = np.array([[ 1,  3,  5,  7,  9],
              [11, 13, 15, 17, 19],
              [21, 23, 25, 27, 29],
              [ 0,  0,  0,  0,  0]])

# Write your expression here
C[0:3, 0:3]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

## Shape

To check the dimensions of a NumPy array, use the `shape` function. In NumPy, shape simply means the dimension of the array, and is represented as a **tuple**.

In [39]:
v = np.array([1, 2, 3, 4, 5])
np.shape(v)

(5,)

In [40]:
v = np.array([[1, 2, 3, 4, 5]])
np.shape(v)

(1, 5)

In [41]:
v = np.array([[1],
              [2],
              [3]])
np.shape(v)

(3, 1)

In [42]:
A = np.array([[1, 2, 3],
              [1, 2, 3]])
np.shape(A)

(2, 3)

In [43]:
A = np.array([[1, 2, 3, 4],
              [1, 2, 3, 4],
              [1, 2, 3, 4],
              [1, 2, 3, 4],
              [1, 2, 3, 4],
              [1, 2, 3, 4]])
np.shape(A)

(6, 4)

## Reshape

The `reshape` function allows you to change the dimensions of an existing vector or matrix by passing a tuple representing the new shape.

In [48]:
# this cell has no output, but be sure to execute it because the next cells use the variables created here
original = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]])

In [45]:
np.reshape(original, (4, 4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [46]:
np.reshape(original, (2, 8))

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [49]:
np.reshape(original, (5, 3)) # This will yield an error because the new shape is not compatible with the original shape

ValueError: cannot reshape array of size 16 into shape (5,3)

You can reshape not only vectors, but also matrices.

In [50]:
# this cell has no output, but be sure to execute it because the next cells use the variables created here
original = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8]])

In [51]:
np.reshape(original, (1, 8))

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [52]:
np.reshape(original, (4, 2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

**Practice!** Reshape the vector `v` to come up with a matrix where the first (leftmost) column contains only 1s.

In [54]:
v = np.array([1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0])

# Write your expression here
np.reshape(v, (3,4))

array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0]])

## Concatenating Vectors and Matrices

The `concatenate` function is a flexible function that can be used to combine mutliple vectors and matrices together. This comes in handy when you need to add a row or a column to an existing matrix.

In [55]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6]])

np.concatenate((A, B))

array([[1, 2],
       [3, 4],
       [5, 6]])

If you specify an `axis` parameter and set it to 1, the concatenation will be performed on the column instead of the row.

In [56]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5],
              [6]])

np.concatenate((A, B), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

Note that for `concatenate` to work, the number of dimensions should be the same. That is, you cannot concatenate a 2-dimensional matrix with a 1-dimensional vector.

## Copying Vectors and Matrices

If you want to make a copy of an existing vector or matrix, you can use the `copy` command. Note that simply assigning the vector or matrix to another variable will not copy it. Instead, both variables will hold a reference to the same vector or matrix.

In [60]:
# If you simply assign to another variable, the vector is not copied
A = np.array([1, 2, 3, 4])
B = A

A[1] = 9

print(A)
print(B)

[1 9 3 4]
[1 9 3 4]


In [61]:
# If you copy, the vector is copied
A = np.array([1, 2, 3, 4])
B = np.copy(A)

A[1] = 9

print(A)
print(B)

[1 9 3 4]
[1 2 3 4]


## Element-Wise Operations

You can perform element wise operations on a vector / matrix and a scalar. This means applying the operation to each element of the vector or matrix.

In [62]:
v = np.array([5, 1, 4, 6, 3, 7, 5, 3, 2])
v > 3

array([ True, False,  True,  True, False,  True,  True, False, False])

In [63]:
v = np.array([[1, 2, 3, 4],
              [4, 3, 2, 1]])
v * 2

array([[2, 4, 6, 8],
       [8, 6, 4, 2]])

You can also perform element wise operations on two vectors / matrices of the same shape. This means applying the operations on the corresponding elements of the two operands.

In [64]:
v = np.array([1, 2, 3, 4, 5, 6, 7, 8])
w = np.array([3, 2, 4, 1, 5, 8, 7, 6])
v == w

array([False,  True, False, False,  True, False,  True, False])

In [66]:
A = np.array([[2, 2],
              [2, 2]])
B = np.array([[1, 2],
              [3, 4]])
A ** B

array([[ 2,  4],
       [ 8, 16]], dtype=int32)

**Practice!** Complete the definition for the matrix `beta` such that the result of adding `alpha` and `beta` is a matrix containing only zeros.

In [70]:
alpha = np.array([[3, 2, 1],
                  [6, 5, 4],
                  [9, 8, 7]])
beta = np.copy(alpha*-1)
# define the beta matrix here

alpha + beta

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Matrix Multiplication and Transpose

There is an important operation in linear algebra called [matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html) (also known as **dot product**). In NumPy, we can perform matrix multiplication using the `dot` function. Note that despite the term "multiplication", do not use the `*` operator to perform matrix multiplication because this will result in element-wise multiplication!

In [71]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[ 7,  8],
              [ 9, 10],
              [11, 12]])
np.dot(A, B)

array([[ 58,  64],
       [139, 154]])

Alternatively, since Python 3.5+ you can use the `@` operator.

In [72]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[ 7,  8],
              [ 9, 10],
              [11, 12]])
A @ B

array([[ 58,  64],
       [139, 154]])

Please remember from your math classes that:

- matrix multiplication is not commutative (the order of the operands matter)
- for the operation to be defined, the number of columns of the first operand should match the number of rows of the second operand.

To perform a [transpose](https://www.mathsisfun.com/definitions/transpose-matrix-.html) operation on a matrix, we can use the `transpose` function.

In [73]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

**Practice!** If you take a row vector and perform matrix multiplication with its transpose, you will get the sum of the squares of each element in the original vector. Verify this by performing this operation on the given vector `v`. This should result into $1^2 + 2^2 + 3^2 + 4^2 = 30$.

In [77]:
v = np.array([[1, 2, 3, 4]])

# Write your expression here

v @ np.transpose(v)

array([[30]])

## Vectorizing Functions

If you have a function that normally operates on a single data point, you can vectorize it so that it will be applied to every element of a vector or matrix. For example, let's say we have this function which counts the number of factors of an integer:

In [78]:
def count_factors(n):
    count = 0
    for i in range(1, n + 1):
        if n % i == 0:
            count = count + 1
    return count

Then, let's say we have a vector `v`:

In [79]:
v = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]])

Let's say we want to count the number of factors of each element in `v`. To do this, we can first vectorize the `count_factors` function:

In [80]:
count_factors_vectorized = np.vectorize(count_factors)

Then, we can pass the vector instead of a single value.

In [81]:
count_factors_vectorized(v)

array([[1, 2, 2, 3, 2, 4, 2, 4, 3, 4, 2, 6, 2, 4, 4]])

This will also work on matrices.

In [82]:
A = np.array([[10, 20],
              [30, 40]])
count_factors_vectorized(A)

array([[4, 6],
       [8, 8]])

**Practice!** Create a function that returns `True` if the integer is even or `False` if the integer is odd. Vectorize this function so that it could be applied to the vector `list`.

In [83]:
list = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])

def is_even(n):
    if n%2 == 0:
        return True
    else:
        return False
    # write your function here

# vectorize the function
is_even_vectorized = np.vectorize(is_even)

# apply it to the list vector
is_even_vectorized(list)


array([[False,  True, False,  True, False,  True, False,  True, False,
         True]])

## Basic Mathematical Operations in NumPy

NumPy provides some common functions for mathematical operations.

In [84]:
# this cell has no output, but be sure to execute it because the next cells use the variables created here
v = np.array([12, 8, 20, 4, 16])

In [85]:
# Get the maximum value
np.max(v)

20

In [86]:
# Get the minimum value
np.min(v)

4

In [87]:
# Get the total value
np.sum(v)

60

If you have a matrix, you can specify the `axis` parameter to specify if the operations are to be performed per column (0) or per row (1).

In [88]:
# this cell has no output, but be sure to execute it because the next cells use the variables created here
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [91]:
# Get the total per column
np.sum(A, axis=0)

array([12, 15, 18])

In [92]:
# Get the total per row
np.sum(A, axis=1)

array([ 6, 15, 24])

In [93]:
# Get the total of all elements in the matrix
np.sum(A)

45

**Practice!** Write code that adds a row to the matrix `grid` containing the highest value in each column. For example, given the matrix:
\begin{equation*}
\begin{bmatrix}
2 & 3 & 1 & 6 \\
4 & 9 & 2 & 7 \\
3 & 3 & 5 & 1
\end{bmatrix}
\end{equation*}
The resulting matrix should be:
\begin{equation*}
\begin{bmatrix}
2 & 3 & 1 & 6 \\
4 & 9 & 2 & 7 \\
3 & 3 & 5 & 1 \\
4 & 9 & 5 & 7
\end{bmatrix}
\end{equation*}

**Note**: `max` returns a 1-dimensional vector, so might need to reshape it to a 2-dimensional row vector before you can concatenate it to the original matrix.

In [109]:
grid = np.array([[2, 3, 1, 6],
                 [4, 9, 2, 7],
                 [3, 3, 5, 1]])

# Write your expression/s here
v_max = np.reshape(np.max(grid, axis=0), (1, 4))

np.concatenate((grid, v_max))

array([[2, 3, 1, 6],
       [4, 9, 2, 7],
       [3, 3, 5, 1],
       [4, 9, 5, 7]])

## What's Next?

This is just the tip of the iceberg for things that you can accomplish with NumPy. As we go through the succeeeding activities in CSMODEL, we will be covering more techniques and functionalities in NumPy. Furthermore, we encourage you not to limit yourselves with the examples presented in this Notebook, but to explore and try out stuff on your own.